name: Build and Deploy Unity WebGL

on:
  push:
    branches:
      - main

jobs:
  # === 1. БИЛД ===
  buildWebGL:
    name: 🧱 Build for WebGL
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # 2️⃣ Кэш библиотеки Unity для ускорения
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-WebGL
          restore-keys: Library-

      # 3️⃣ Освобождаем место на диске (GitHub runners часто переполнены)
      - name: Free up disk space
        uses: jlumbroso/free-disk-space@v1.3.1

      # 4️⃣ Полностью очищаем предыдущие сборки
      - name: Clean old build artifacts
        run: |
          echo "🧹 Cleaning old build artifacts..."
          rm -rf build/WebGL || true
          mkdir -p build/WebGL

      # 5️⃣ Собираем Unity WebGL проект через GameCI
      - name: Build project with Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          targetPlatform: WebGL
          unityVersion: 2022.3.5f1
          buildsPath: build/WebGL

      # 6️⃣ Загружаем результат как артефакт
      - name: Upload WebGL build
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-build
          path: build/WebGL

  # === 2. ДЕПЛОЙ ===
  deployToPages:
    name: 🚀 Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: buildWebGL

    steps:
      # 1️⃣ Скачиваем артефакт из предыдущего job
      - name: Download WebGL build
        uses: actions/download-artifact@v4
        with:
          name: WebGL-build
          path: build

      # 2️⃣ Публикуем на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/WebGL

      # 3️⃣ Лог финальной ссылки на проект
      - name: Print deployment URL
        run: echo "🌐 Your build is live at: https://artrmiys.github.io/Our_Project_Simple/"
