name: Build project

on:
  push:
  pull_request:

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL               # WebGL build

    steps:
      # === 1. Checkout repository ===
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # === 2. Cache Unity Library to speed up builds ===
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      # === 3. Free up disk space (mostly for Android/iOS builds) ===
      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1

      # === 4. Build using GameCI Unity Builder ===
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: 2022.3.5f1
          buildsPath: build/${{ matrix.targetPlatform }}

      # === 5. Upload build artifact ===
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
