name: Build Unity Windows

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-windows:
    name: 🧱 Build Unity (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Clean old build & Library
        shell: bash
        run: |
          rm -rf Build/Windows || true
          rm -rf Build/StandaloneWindows64 || true
          rm -rf Library || true
          echo "🧹 Cleaned old build and Library"

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Build Unity project (Windows)
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          targetPlatform: StandaloneWindows64
          unityVersion: 2022.3.5f1
          buildsPath: Build

      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: Build/StandaloneWindows64
