name: Build Windows

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  buildWindows:
    name: 🪟 Build Windows Standalone
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false

      - name: Build Windows with Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          targetPlatform: StandaloneWindows64
          buildsPath: build/Windows

      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: build/Windows
