name: Build and Deploy Unity WebGL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Используем docker без лицензии
      - name: Build Unity WebGL (no license)
        uses: webbertakken/unity-builder@v2
        with:
          projectPath: .
          targetPlatform: WebGL
          unityVersion: 2022.3.5f1

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/WebGL/WebGLBuild
