name: Build and Deploy Unity WebGL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build WebGL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build project for WebGL
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.5f1
          targetPlatform: WebGL
          projectPath: .
          buildName: WebGLBuild
          buildsPath: build

      - name: Upload WebGL artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-build
          path: build/WebGLBuild

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download WebGL artifact
        uses: actions/download-artifact@v4
        with:
          name: WebGL-build
          path: build/WebGLBuild

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/WebGLBuild
